In [7]:
def sum_arr ( nums):
    if len(nums) ==0:
        return []
    sum_nums = [nums[0]]
    for i in range(1,len(nums)):
        temp_sum = nums[i]+sum_nums[i-1]
        sum_nums.append(temp_sum)
    return sum_nums

In [8]:
a = [3,1,2,10,1]
b = sum_arr(a)
print(b)

[3, 4, 6, 16, 17]

In [12]:
a = [0]
b = sum_arr(a)
print(b)

[0]

In [19]:
def minimum_operator(n):
    result = 0
    if n%2 ==1:
        l = n- n//2*2 - 1
        r = n- n//2*2 + 1
    else:
        l = n/2 -1
        r = n/2 
    for i in range(n//2):
        temp = (2*l+1 )/2 -(2*r+1)/2
        if temp <0:
            temp = -temp
        result += temp
        l-=1
        r+=1
    return result

In [24]:
a = minimum_operator(10)
print(a)

25.0

In [25]:
import pandas as pd

In [26]:
df_covid = pd.read_csv("Coronavirus_COVID-19_Cases.csv")

In [27]:
df_covid.head()

,X,Y,OBJECTID,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Recovered,Deaths,Active,Admin2,FIPS,Combined_Key
0,67.709953,33.93911,1,NaN,Afghanistan,2021/06/25 13:21:42+00,33.93911,67.709953,111592,66799,4519,40274,NaN,NaN,Afghanistan
1,20.168300,41.15330,2,NaN,Albania,2021/06/25 13:21:42+00,41.15330,20.168300,132499,129966,2455,78,NaN,NaN,Albania
2,1.659600,28.03390,3,NaN,Algeria,2021/06/25 13:21:42+00,28.03390,1.659600,137403,95599,3669,38135,NaN,NaN,Algeria
3,1.521800,42.50630,4,NaN,Andorra,2021/06/25 13:21:42+00,42.50630,1.521800,13877,13694,127,56,NaN,NaN,Andorra
4,17.873900,-11.20270,5,NaN,Angola,2021/06/25 13:21:42+00,-11.20270,17.873900,38091,32340,881,4870,NaN,NaN,Angola

In [28]:
import requests

In [29]:
response = requests.get("https://covid-api.mmediagroup.fr/v1/cases")

In [30]:
response?

Type:        Response
String form: <Response [200]>
File:        c:\users\dell\anaconda31\lib\site-packages\requests\models.py
Docstring:
The :class:`Response <Response>` object, which contains a
server's response to an HTTP request.

In [36]:
df_json = pd.DataFrame.from_dict(response.json())

In [78]:
countrys  = list(df_json.columns.values)
df_case = pd.DataFrame(columns = ['confirmed', 'recovered', 'deaths', 'country', 'population',
       'sq_km_area', 'life_expectancy', 'elevation_in_meters',
       'continent', 'abbreviation', 'location', 'iso', 'capital_city',
       'lat', 'long', 'updated'])

In [80]:
for country in countrys:
    print(country)
    str_request = "https://covid-api.mmediagroup.fr/v1/cases?country="+country
    response = requests.get(str_request)
    dict_ = dict(response.json()["All"])
    df_case = df_case.append(dict_, ignore_index=True)

Afghanistan
Albania
Algeria
Andorra
Angola
Antigua and Barbuda
Argentina
Armenia
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brazil
Brunei
Bulgaria
Burkina Faso
Burma
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Central African Republic
Chad
Chile
China
Colombia
Comoros
Congo (Brazzaville)
Congo (Kinshasa)
Costa Rica
Cote d'Ivoire
Croatia
Cuba
Cyprus
Czechia
Denmark
Diamond Princess
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Eswatini
Ethiopia
Fiji
Finland
France
Gabon
Gambia
Georgia
Germany
Ghana
Greece
Grenada
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Holy See
Honduras
Hungary
Iceland
India
Indonesia
Iran
Iraq
Ireland
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Korea, South
Kosovo
Kuwait
Kyrgyzstan
Laos
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
MS Zaandam
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Micronesia
Moldova
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Namibia
Nepal
Netherlands
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
Norway
Oman
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Qatar
Romania
Russia
Rwanda
Saint Kitts and Nevis
Saint Lucia
Saint Vincent and the Grenadines
Samoa
San Marino
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Solomon Islands
Somalia
South Africa
South Sudan
Spain
Sri Lanka
Sudan
Summer Olympics 2020
Suriname
Sweden
Switzerland
Syria
Taiwan*
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Trinidad and Tobago
Tunisia
Turkey
Uganda
Ukraine
United Arab Emirates
United Kingdom
Uruguay
Uzbekistan
Vanuatu
Venezuela
Vietnam
West Bank and Gaza
Yemen
Zambia
Zimbabwe
US
Global

In [81]:
df_case.head()

,confirmed,recovered,deaths,country,population,sq_km_area,life_expectancy,elevation_in_meters,continent,abbreviation,location,iso,capital_city,lat,long,updated
0,111592,66799,4519,Afghanistan,35530081,652090,45.9,None,Asia,AF,Southern and Central Asia,4,Kabul,33.93911,67.709953,2021/06/25 13:21:42+00
1,132499,129966,2455,Albania,2930187,28748,71.6,None,Europe,AL,Southern Europe,8,Tirana,41.1533,20.1683,2021/06/25 13:21:42+00
2,137403,95599,3669,Algeria,41318142,2381741,69.7,800,Africa,DZ,Northern Africa,12,Alger,28.0339,1.6596,2021/06/25 13:21:42+00
3,13877,13694,127,Andorra,76965,468,83.5,"1,996",Europe,AD,Southern Europe,20,Andorra la Vella,42.5063,1.5218,2021/06/25 14:21:45+00
4,38091,32340,881,Angola,29784193,1246700,38.3,"1,112",Africa,AO,Central Africa,24,Luanda,-11.2027,17.8739,2021/06/25 14:21:45+00

In [82]:
df_case.to_csv('covid_case.csv',sep=',', index=False)

In [97]:
df_vaccine = pd.DataFrame(columns = ["administered",
    "people_vaccinated",
    "people_partially_vaccinated",
    "country",
    "population",
    "sq_km_area",
    "life_expectancy",
    "elevation_in_meters",
    "continent",
    "abbreviation",
    "location",
    "iso",
    "capital_city",
    "lat",
    "long",
    "updated"])

In [98]:
error_country = []
for country in countrys:
    try:
        print(country)
        str_request = "https://covid-api.mmediagroup.fr/v1/vaccines?country="+country
        response = requests.get(str_request)
        dict_ = dict(response.json()["All"])
        df_vaccine = df_vaccine.append(dict_, ignore_index=True)
    except :
        error_country.append(country)
        continue

Afghanistan
Albania
Algeria
Andorra
Angola
Antigua and Barbuda
Argentina
Armenia
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brazil
Brunei
Bulgaria
Burkina Faso
Burma
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Central African Republic
Chad
Chile
China
Colombia
Comoros
Congo (Brazzaville)
Congo (Kinshasa)
Costa Rica
Cote d'Ivoire
Croatia
Cuba
Cyprus
Czechia
Denmark
Diamond Princess
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Eswatini
Ethiopia
Fiji
Finland
France
Gabon
Gambia
Georgia
Germany
Ghana
Greece
Grenada
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Holy See
Honduras
Hungary
Iceland
India
Indonesia
Iran
Iraq
Ireland
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Korea, South
Kosovo
Kuwait
Kyrgyzstan
Laos
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
MS Zaandam
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Micronesia
Moldova
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Namibia
Nepal
Netherlands
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
Norway
Oman
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Qatar
Romania
Russia
Rwanda
Saint Kitts and Nevis
Saint Lucia
Saint Vincent and the Grenadines
Samoa
San Marino
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Solomon Islands
Somalia
South Africa
South Sudan
Spain
Sri Lanka
Sudan
Summer Olympics 2020
Suriname
Sweden
Switzerland
Syria
Taiwan*
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Trinidad and Tobago
Tunisia
Turkey
Uganda
Ukraine
United Arab Emirates
United Kingdom
Uruguay
Uzbekistan
Vanuatu
Venezuela
Vietnam
West Bank and Gaza
Yemen
Zambia
Zimbabwe
US
Global

In [101]:
error_country

['Benin',
 'Burkina Faso',
 'Burundi',
 'Cabo Verde',
 'Central African Republic',
 'Chad',
 'Comoros',
 'Congo (Brazzaville)',
 'Congo (Kinshasa)',
 'Cuba',
 'Czechia',
 'Diamond Princess',
 'Djibouti',
 'Eritrea',
 'Guinea-Bissau',
 'Haiti',
 'Holy See',
 'Kiribati',
 'Korea, South',
 'Lesotho',
 'Liberia',
 'Libya',
 'MS Zaandam',
 'Madagascar',
 'Niger',
 'Samoa',
 'Somalia',
 'Summer Olympics 2020',
 'Switzerland',
 'Tajikistan',
 'Tanzania',
 'Timor-Leste',
 'Vanuatu',
 'West Bank and Gaza',
 'Yemen']

In [99]:
df_vaccine.to_csv('covid_vaccine.csv',sep=',', index=False)

In [100]:
df_vaccine.head()

,administered,people_vaccinated,people_partially_vaccinated,country,population,sq_km_area,life_expectancy,elevation_in_meters,continent,abbreviation,location,iso,capital_city,lat,long,updated
0,765890,183762,582128,Afghanistan,35530081,652090,45.9,None,Asia,AF,Southern and Central Asia,4,Kabul,NaN,NaN,2021/06/25 00:00:00+00
1,922886,385868,537018,Albania,2930187,28748,71.6,None,Europe,AL,Southern Europe,8,Tirana,NaN,NaN,2021/06/25 00:00:00+00
2,2500000,0,2500000,Algeria,41318142,2381741,69.7,800,Africa,DZ,Northern Africa,12,Alger,NaN,NaN,2021/06/25 00:00:00+00
3,63272,24598,38667,Andorra,76965,468,83.5,"1,996",Europe,AD,Southern Europe,20,Andorra la Vella,NaN,NaN,2021/06/25 00:00:00+00
4,1432699,523580,909119,Angola,29784193,1246700,38.3,"1,112",Africa,AO,Central Africa,24,Luanda,NaN,NaN,2021/06/25 00:00:00+00

In [117]:
df_death = pd.DataFrame(columns = ["country", "date", "numbers","status"])
error_country = []
for country in countrys:
    try:
        print(country)
        str_request = "https://covid-api.mmediagroup.fr/v1//history?country="+country+"&status=deaths"
        response = requests.get(str_request)
        dict_date = dict(response.json()["All"]["dates"])
        ls_dates = list(dict_date.keys())
        ls_numbers = list(dict_date.values())
        ls_countrys = [country]*len(dates)
        ls_status = ["deaths"]*len(dates)
        df_deathe_temp = pd.DataFrame({"country":ls_countrys, "date":ls_dates, "numbers":ls_numbers,"status": ls_status})
        df_death = df_death.append(df_deathe_temp, ignore_index=True)
    except :
        error_country.append(country)
        continue

Afghanistan
Albania
Algeria
Andorra
Angola
Antigua and Barbuda
Argentina
Armenia
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brazil
Brunei
Bulgaria
Burkina Faso
Burma
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Central African Republic
Chad
Chile
China
Colombia
Comoros
Congo (Brazzaville)
Congo (Kinshasa)
Costa Rica
Cote d'Ivoire
Croatia
Cuba
Cyprus
Czechia
Denmark
Diamond Princess
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Eswatini
Ethiopia
Fiji
Finland
France
Gabon
Gambia
Georgia
Germany
Ghana
Greece
Grenada
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Holy See
Honduras
Hungary
Iceland
India
Indonesia
Iran
Iraq
Ireland
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Korea, South
Kosovo
Kuwait
Kyrgyzstan
Laos
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
MS Zaandam
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Micronesia
Moldova
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Namibia
Nepal
Netherlands
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
Norway
Oman
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Qatar
Romania
Russia
Rwanda
Saint Kitts and Nevis
Saint Lucia
Saint Vincent and the Grenadines
Samoa
San Marino
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Solomon Islands
Somalia
South Africa
South Sudan
Spain
Sri Lanka
Sudan
Summer Olympics 2020
Suriname
Sweden
Switzerland
Syria
Taiwan*
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Trinidad and Tobago
Tunisia
Turkey
Uganda
Ukraine
United Arab Emirates
United Kingdom
Uruguay
Uzbekistan
Vanuatu
Venezuela
Vietnam
West Bank and Gaza
Yemen
Zambia
Zimbabwe
US
Global

In [108]:

str_request = "https://covid-api.mmediagroup.fr/v1//history?country=Germany&status=deaths"
response = requests.get(str_request)
dict_date = dict(response.json()["All"]["dates"])
dates = list(dict_date.keys())
numbers = list(dict_date.values())
country = ['a']*len(dates)

In [118]:
error_country

[]

In [121]:
df_death.head()

       country        date numbers  status
0  Afghanistan  2021-06-24    4452  deaths
1  Afghanistan  2021-06-23    4366  deaths
2  Afghanistan  2021-06-22    4293  deaths
3  Afghanistan  2021-06-21    4215  deaths
4  Afghanistan  2021-06-20    3934  deaths

In [120]:
df_death.to_csv('covid_his_dead.csv',sep=',', index=False)

In [122]:
error_country = []
for country in countrys:
    try:
        print(country)
        str_request = "https://covid-api.mmediagroup.fr/v1//history?country="+country+"&status=confirmed"
        response = requests.get(str_request)
        dict_date = dict(response.json()["All"]["dates"])
        ls_dates = list(dict_date.keys())
        ls_numbers = list(dict_date.values())
        ls_countrys = [country]*len(dates)
        ls_status = ["confirmed"]*len(dates)
        df_confirmed_temp = pd.DataFrame({"country":ls_countrys, "date":ls_dates, "numbers":ls_numbers,"status": ls_status})
        df_death = df_death.append(df_confirmed_temp, ignore_index=True)
    except :
        error_country.append(country)
        continue
df_death.to_csv('covid_his_dead_confirm.csv',sep=',', index=False)

Afghanistan
Albania
Algeria
Andorra
Angola
Antigua and Barbuda
Argentina
Armenia
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brazil
Brunei
Bulgaria
Burkina Faso
Burma
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Central African Republic
Chad
Chile
China
Colombia
Comoros
Congo (Brazzaville)
Congo (Kinshasa)
Costa Rica
Cote d'Ivoire
Croatia
Cuba
Cyprus
Czechia
Denmark
Diamond Princess
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Eswatini
Ethiopia
Fiji
Finland
France
Gabon
Gambia
Georgia
Germany
Ghana
Greece
Grenada
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Holy See
Honduras
Hungary
Iceland
India
Indonesia
Iran
Iraq
Ireland
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Korea, South
Kosovo
Kuwait
Kyrgyzstan
Laos
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
MS Zaandam
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Micronesia
Moldova
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Namibia
Nepal
Netherlands
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
Norway
Oman
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Qatar
Romania
Russia
Rwanda
Saint Kitts and Nevis
Saint Lucia
Saint Vincent and the Grenadines
Samoa
San Marino
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Solomon Islands
Somalia
South Africa
South Sudan
Spain
Sri Lanka
Sudan
Summer Olympics 2020
Suriname
Sweden
Switzerland
Syria
Taiwan*
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Trinidad and Tobago
Tunisia
Turkey
Uganda
Ukraine
United Arab Emirates
United Kingdom
Uruguay
Uzbekistan
Vanuatu
Venezuela
Vietnam
West Bank and Gaza
Yemen
Zambia
Zimbabwe
US
Global

In [124]:
error_country = []
for country in countrys:
    try:
        print(country)
        str_request = "https://covid-api.mmediagroup.fr/v1//history?country="+country+"&status=recovered"
        response = requests.get(str_request)
        dict_date = dict(response.json()["All"]["dates"])
        ls_dates = list(dict_date.keys())
        ls_numbers = list(dict_date.values())
        ls_countrys = [country]*len(dates)
        ls_status = ["recovered"]*len(dates)
        df_recovered_temp = pd.DataFrame({"country":ls_countrys, "date":ls_dates, "numbers":ls_numbers,"status": ls_status})
        df_death = df_death.append(df_recovered_temp, ignore_index=True)
    except :
        error_country.append(country)
        continue
df_death.to_csv('covid_his_dead_confirm_recover.csv',sep=',', index=False)

Afghanistan
Albania
Algeria
Andorra
Angola
Antigua and Barbuda
Argentina
Armenia
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brazil
Brunei
Bulgaria
Burkina Faso
Burma
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Central African Republic
Chad
Chile
China
Colombia
Comoros
Congo (Brazzaville)
Congo (Kinshasa)
Costa Rica
Cote d'Ivoire
Croatia
Cuba
Cyprus
Czechia
Denmark
Diamond Princess
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Eswatini
Ethiopia
Fiji
Finland
France
Gabon
Gambia
Georgia
Germany
Ghana
Greece
Grenada
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Holy See
Honduras
Hungary
Iceland
India
Indonesia
Iran
Iraq
Ireland
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Korea, South
Kosovo
Kuwait
Kyrgyzstan
Laos
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
MS Zaandam
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Micronesia
Moldova
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Namibia
Nepal
Netherlands
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
Norway
Oman
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Qatar
Romania
Russia
Rwanda
Saint Kitts and Nevis
Saint Lucia
Saint Vincent and the Grenadines
Samoa
San Marino
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Solomon Islands
Somalia
South Africa
South Sudan
Spain
Sri Lanka
Sudan
Summer Olympics 2020
Suriname
Sweden
Switzerland
Syria
Taiwan*
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Trinidad and Tobago
Tunisia
Turkey
Uganda
Ukraine
United Arab Emirates
United Kingdom
Uruguay
Uzbekistan
Vanuatu
Venezuela
Vietnam
West Bank and Gaza
Yemen
Zambia
Zimbabwe
US
Global